name: Save Hello World with Timestamp

on:
  schedule:
    # Runs every minute
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  save_message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Save Hello World and Timestamp
        run: |
          echo "Hello, World! $(date)" >> hello_world_timestamps.txt
      
