name: Save Hello World with Timestamp

on:
  schedule:
    # Runs every minute
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  save_message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Save Hello World and Timestamp
        run: |
          echo "Hello, World! $(date)" > hello_world_timestamps.txt
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add hello_world_timestamps.txt
          git commit -m "Add Hello World with Timestamp" || exit 0  # Exit gracefully if no changes
          git push
      
